const data = {
    data: [{
      title: "1",
      task: "2",
      lastAction: "3",
      timestamp: "4",
      elapsed: "5",
      remaining: "6",
      status: "7",
      notes: "8",
      v1: 220.13,
      v2: 330.1
    }, {
      title: "1",
      task: "2",
      lastAction: "3",
      timestamp: "4",
      elapsed: "5",
      remaining: "6",
      status: "7",
      notes: "8",
      v1: 350.63,
      v2: 290.35
    }, {
      title: "1",
      task: "2",
      lastAction: "3",
      timestamp: "4",
      elapsed: "5",
      remaining: "6",
      status: "7",
      notes: "8",
      v1: 430.83,
      v2: 420.93
    }, {
      title: "1",
      task: "2",
      lastAction: "3",
      timestamp: "4",
      elapsed: "5",
      remaining: "6",
      status: "7",
      notes: "8",
      v1: 32.52,
      v2: 330.1
    }, {
      title: "1",
      task: "2",
      lastAction: "3",
      timestamp: "4",
      elapsed: "5",
      remaining: "6",
      status: "7",
      notes: "8",
      v1: 220.67,
      v2: 190.36
    }, {
      title: "1",
      task: "2",
      lastAction: "3",
      timestamp: "4",
      elapsed: "5",
      remaining: "6",
      status: "7",
      notes: "8",
      v1: 220.85,
      v2: 100.34
    }]
  }
  
  export { data };